### ISSUE TITLE
Could not read FLICKR_APP_KEY and FLICKR_APP_SECRET from environment

### ISSUE THREAD

**Issue by egorodesa** [antoinerousseau/flickr2google#6]
./start.js
2020-09-18 18:11:41 Error: Could not read FLICKR_APP_KEY and FLICKR_APP_SECRET from environment.

**Comment by antoinerousseau** [comment]
Did you set those constants (directly or as [explained in the README](https://github.com/antoinerousseau/flickr2google#setup))?

**Comment by egorodesa** [comment]
> Did you set those constants (directly or as [explained in the README](https://github.com/antoinerousseau/flickr2google#setup))?

sure

**Comment by antoinerousseau** [comment]
please give more details, environment and context if you want some help

**Comment by egorodesa** [comment]
node start.js
2020-12-21 12:37:03 Error: Could not read FLICKR_APP_KEY and FLICKR_APP_SECRET from environment.
    at module.exports (/home/egor/flickr2google/flickr.js:13:11)
    at main (/home/egor/flickr2google/start.js:18:37)
    at Object.<anonymous> (/home/egor/flickr2google/start.js:164:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

node -v
v12.20.0
ubuntu 20.04.1

**Comment by antoinerousseau** [comment]
check the content of `/home/egor/flickr2google/.env`

**Comment by egorodesa** [comment]
> check the content of `/home/egor/flickr2google/.env`

sure, this is only what I fixed from the beginning. That's why the question 
![Screenshot from 2020-12-22 16-29-24](https://user-images.githubusercontent.com/245831/102899551-c27f9100-4473-11eb-9c2e-0567d17896b9.png)

**Comment by antoinerousseau** [comment]
Your file is named `egor.env` not `.env`, just name it `.env` as instructed.

**Comment by egorodesa** [comment]
@antoinerousseau thx so much, now it works. really seems like a very quality app.
for now, it is another problem:
![Screenshot from 2021-02-13 10-30-49](https://user-images.githubusercontent.com/245831/107845891-bbc42900-6de7-11eb-9616-8691aa0f6a72.png)

**Comment by antoinerousseau** [comment]
This error is explained in the README...
https://github.com/antoinerousseau/flickr2google#limitations
